import PersonIcon from '@mui/icons-material/Person';
import InsertDriveFileIcon from '@mui/icons-material/InsertDriveFile';

export const buttonGroupData = [{
        id:'buttonRegistMentor',
        label: 'Become a mentor',
        variant: 'text',
        color: 'rgba(0, 0, 0, 0.6)',
        startIcon: null,
        fontSize: '14px',
        width: 'auto',
      },
      {
        id:'buttonLogin',
        label: 'LOGIN',
        variant: 'outlined',
        color: 'rgba(0, 0, 0, 0.87)',
        bordercolor: 'rgba(0, 0, 0, 0.87)',
        startIcon: <PersonIcon />,
        fontSize: '14px',
        width: 'auto',
      },
      {
        id:'buttonRegistration',
        label: 'REGISTER',
        variant: 'outlined',
        color: 'rgba(0, 0, 0, 0.87)',
        bordercolor: 'rgba(0, 0, 0, 0.87)',
        startIcon: null,
        fontSize: '14px',
        width: 'auto',
      },
    ];

  export const buttonAdminGroupData = [
    {
      id:'dashboardAdmin',
      label: 'Dashboard',
      variant: 'outlined',
      color: '#3B72FF',
      bordercolor: '#3B72FF',
      startIcon: <InsertDriveFileIcon sx={{ color: '#3B72FF' }} />,
      fontSize: '14px',
      width: 'auto',
    },
    {
      id:'courseAdmin',
      label: 'Course',
      variant: 'outlined',
      color: '#900c3f',
      bordercolor: '#900c3f',
      startIcon: <InsertDriveFileIcon sx={{ color: '#900c3f' }} />,
      fontSize: '14px',
      width: 'auto',
    },
    {
      id:'discussionAdmin',
      label: 'Discussion',
      variant: 'outlined',
      color: 'green',
      bordercolor: 'green',
      startIcon: <InsertDriveFileIcon sx={{ color: 'green' }} />,
      fontSize: '14px',
      width: 'auto',
    },
    {
      id:'feedbackAdmin',
      label: 'Feedback',
      variant: 'outlined',
      color: '#255e79',
      bordercolor: '#255e79',
      startIcon: <InsertDriveFileIcon sx={{ color: '#255e79' }} />,
      fontSize: '14px',
      width: 'auto',
    },
    {
      id:'subsAdmin',
      label: 'Subscription',
      variant: 'outlined',
      color: 'orange',
      bordercolor: 'orange',
      startIcon: <InsertDriveFileIcon sx={{ color: 'orange' }} />,
      fontSize: '14px',
      width: 'auto',
    },
    {
      id:'userListAdmin',
      label: 'Mentor & Mentee List',
      variant: 'outlined',
      color: 'purple',
      bordercolor: 'purple',
      startIcon: <InsertDriveFileIcon sx={{ color: 'purple' }} />,
      fontSize: '14px',
      width: 'auto',
    },
    {
      id:'announAdmin',
      label: 'Announcement',
      variant: 'outlined',
      color: '#d62828',
      bordercolor: '#d62828',
      startIcon: <InsertDriveFileIcon sx={{ color: '#d62828' }} />,
      fontSize: '14px',
      width: 'auto',
    },
  ];

  export const buttonMentorGroupData = [
  {
    id:'courseMentor',
    label: 'Course',
    variant: 'outlined',
    color: '#900c3f',
    bordercolor: '#900c3f',
    startIcon: <InsertDriveFileIcon sx={{ color: '#900c3f' }} />,
    fontSize: '14px',
    width: 'auto',
  },
  {
    id:'discussion',
    label: 'Discussion',
    variant: 'outlined',
    color: 'green',
    bordercolor: 'green',
    startIcon: <InsertDriveFileIcon sx={{ color: 'green' }} />,
    fontSize: '14px',
    width: 'auto',
  },
  {
    id:'feedback',
    label: 'Feedback',
    variant: 'outlined',
    color: '#255e79',
    bordercolor: '#255e79',
    startIcon: <InsertDriveFileIcon sx={{ color: '#255e79' }} />,
    fontSize: '14px',
    width: 'auto',
  },
  {
    id:'menteeList',
    label: 'Mentee',
    variant: 'outlined',
    color: 'purple',
    bordercolor: 'purple',
    startIcon: <InsertDriveFileIcon sx={{ color: 'purple' }} />,
    fontSize: '14px',
    width: 'auto',
  },
  {
    id:'announcement',
    label: 'Announcement',
    variant: 'outlined',
    color: '#d62828',
    bordercolor: '#d62828',
    startIcon: <InsertDriveFileIcon sx={{ color: '#d62828' }} />,
    fontSize: '14px',
    width: 'auto',
  },
  {
    id:'subscription',
    label: 'Subscription',
    variant: 'outlined',
    color: 'orange',
    bordercolor: 'orange',
    startIcon: <InsertDriveFileIcon sx={{ color: 'orange' }} />,
    fontSize: '14px',
    width: 'auto',
  },
];

export const buttonMenteeGroupData = [
{
  id:'courseMentee',
  label: 'Course',
  variant: 'outlined',
  color: '#900c3f',
  bordercolor: '#900c3f',
  startIcon: <InsertDriveFileIcon sx={{ color: '#900c3f' }} />,
  fontSize: '14px',
  width: 'auto',
},
{
  id:'discussion',
  label: 'Discussion',
  variant: 'outlined',
  color: 'green',
  bordercolor: 'green',
  startIcon: <InsertDriveFileIcon sx={{ color: 'green' }} />,
  fontSize: '14px',
  width: 'auto',
},
{
  id:'feedback',
  label: 'Feedback',
  variant: 'outlined',
  color: '#255e79',
  bordercolor: '#255e79',
  startIcon: <InsertDriveFileIcon sx={{ color: '#255e79' }} />,
  fontSize: '14px',
  width: 'auto',
},
{
  id:'mentorList',
  label: 'Mentor',
  variant: 'outlined',
  color: 'purple',
  bordercolor: 'purple',
  startIcon: <InsertDriveFileIcon sx={{ color: 'purple' }} />,
  fontSize: '14px',
  width: 'auto',
},
{
  id:'announcement',
  label: 'Announcement',
  variant: 'outlined',
  color: '#d62828',
  bordercolor: '#d62828',
  startIcon: <InsertDriveFileIcon sx={{ color: '#d62828' }} />,
  fontSize: '14px',
  width: 'auto',
},
{
  id:'subscription',
  label: 'Subscription',
  variant: 'outlined',
  color: 'orange',
  bordercolor: 'orange',
  startIcon: <InsertDriveFileIcon sx={{ color: 'orange' }} />,
  fontSize: '14px',
  width: 'auto',
},
];
