export const initialRegMentee = {
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  confirmPassword: "",
  address: "",
  gender: "",
  education: "",
  graduationYear: "",
  major: "",
  university: "",
  motivation: "",
};

export const initialRegMentor = {
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  confirmPassword: "",
  address: "",
  gender: "",
  education: "",
  graduationYear: "",
  major: "",
  university: "",
  job: "",
  jobField: "",
  exp: "",
  skill: "",
  motivation: "",
};
